spring:
  mail:
    host: smtp.163.com # 网站发送邮件邮箱服务 host
    port: 465
    username: mqkim0525@163.com   # 请填写您的163邮箱地址
    password: JRbWC33LbDyeBUB6  # 请填写您的163邮箱授权码（不是登录密码）
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
mail:
  address: mqkim0525@163.com   # 请填写您的163邮箱地址（与上面保持一致）

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  endpoint: http://localhost:9000
  access-key: root
  secret-key: 123456789
  bucket-name: user01